from typing import List, Dict, TypedDict
import datetime

class GrinderProfile(TypedDict):
    """
    TypedDict for Grinder Profile which contains the structure of the Grinder Profile

    Attributes
    ------------
    `name:` name of the profile
    `role:` role id of the profile
    `payment:` payment amount
    `frequency:` frequency of payment
    """
    
    name: str
    role: int
    payment: int
    frequency: int


class GrinerTrail(TypedDict):
    """
    TypedDict for Grinder Trail which contains the structure of the Grinder Trail

    Attributes
    ------------
    `role:` role id of the trail
    `duration:` duration of the trail
    """

    role: int
    duration: int


class GrinderConfig(TypedDict):
    """
    TypedDict for Grinder Config which contains the structure of the Grinder Config

    Attributes
    ------------
    `_id:` guild id
    `payment_channel:` payment channel id
    `manager_roles:` list of manager roles
    `base_role:` base role id
    `max_profiles`: maximum profiles
    `profile:` dict of profiles
    `trail:` trail
    """

    _id: int
    payment_channel: int
    manager_roles: List[int]
    base_role: int
    max_profiles: int
    profile: Dict[str, GrinderProfile]
    trail: GrinerTrail
    missed_payment_limit: int

class GrinderPayment(TypedDict):
    """
    TypedDict for Grinder Payment which contains the structure of the Grinder Payment

    Attributes
    ------------
    `total:` total payment
    `due:` due payment
    `credits:` credits
    `last_payment:` last payment date
    `next_payment:` next payment date
    """

    total: int
    due: int
    credits: int
    last_payment: datetime.datetime
    next_payment: datetime.datetime

class GrinderAccount(TypedDict):
    """
    TypedDict for Grinder Account which contains the structure of the Grinder Account

    Attributes
    ------------
    `_id:` object id auto generated by mongodb
    `guild:` guild id
    `user:` user id
    `profile:` profile name
    `payment:` payment details
    `profile_role:` profile role id
    """

    guild: int
    user: int
    profile: str
    payment: GrinderPayment
    profile_role: int