name: Server Deployment Flow

on:
  workflow_run:
    workflows: ["Syntax check"]
    types:
      - completed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: hwalker928/ptero-gitsync@v1.0
        with:
          panel-url: ${{ secrets.PANEL_URL }}
          api-key: ${{ secrets.API_KEY }}
          server-id: ${{ secrets.SERVER_ID }}
