name: Server Deployment Flow

on:
  workflow_run:
    workflows: ["Syntax check"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Connect, Pull and Cleanup
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
            cd ${{ secrets.PATH }} && \
            git checkout ${{ secrets.BRANCH }} && \
            git pull origin ${{ secrets.BRANCH }} && \
            git remote prune origin && \
            git gc --prune=now"

      - name: Cleanup Local SSH Key
        if: always()
        run: rm -f ~/.ssh/deploy_key
